title: Gabriel Deza
description: PhD student in Industrial Engineering at Tel Aviv University
url: https://gabrieldeza.github.io
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
