title: Gabriel Deza
description: Gabriel Deza is a PhD student at Tel Aviv University researching transportation optimization, line planning, timetabling, and network design.
url: https://gabrieldeza.github.io
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
